config/routes.rb
Blogger::Application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # when browser receives a request, it will go to the router first to decide what the request is trying to do or interact with

  # the "resources" tells Rails that we have a resource named "articles" and the router should expect the request to follow RESTful (REpresentational State Transfer) model of the web interaction. For ex, when you make a request like http://localhost:3000/articles/, the router will understand you’re looking for a listing of the articles, and http://localhost:3000/articles/new means you’re trying to create a new article.

  # this is to set the starter page at http://localhost:3000/
  root to: 'articles#index'
  # if we comment out this line, the Terminal will say: "You don't have any routes defined!""
  resources :articles do
    resources :comments
  end
  resources :tags

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# no attr defined inside the model.  how does Rails know that an Article should have a title, a body, etc? The answer is a technique called reflection. Rails queries the database, looks at the articles table, and assumes that whatever columns that table has should be the attributes for the model.
class Article < ApplicationRecord
  has_many :comments
  has_many :taggings
  # an article has a list of tags through the ralationship of taggings.
  has_many :tags, through: :taggings
  # This has_attached_file method is part of the paperclip library.
  # As of version 4.0, all attachments are required to include a content_type validation, a file_name validation, or to explicitly state that they’re not going to have either. Paperclip raises MissingRequiredValidatorError error if you do not do this.
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/ipg", "image/jpeg", "image/png"]

  def tag_list()
    # if we only do tags.join(", "), the array of tags will show sth like this: "#<Tag:0x007fe4d60c2430>, #<Tag:0x007fe4d617da50>", which is ugly, so we want to 1)convert all tag objects to an array of tag names, 2)join the arr of tag names together
    # tags.join(", ")

    # "self.method" create methods that don't require objects to be created first -> a class method
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

# create an attribute named "tag_list"
# the next step is to go through each of those tag_names and find or create a tag with that name
# about the equal sign after tag_list  http://stackoverflow.com/questions/5398919/what-does-the-equal-symbol-do-when-put-after-the-method-name-in-a-method-d
def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  #A comment relates to a single article, it "belongs to" an article. 
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #When user click on the title, the browser will be directed to this URL: http://localhost:3000/articles/1. We use the number on the end of the URL to find the article in the database.
  # "find" is a class method. params[:id] is the key
  include ArticlesHelper
  def index
    # instance var: we want the list of articles to be accessible from both the controller and the view
    # in Rails' controller, there's a hack which allows instance var to be automatically transferred from the controller to the object which renders in the view template
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    # if we use @comment = @article.comments.new here, it will create an extra "Comment by" line. The reason is @article.comments.new has added the new Comment to the in-memory collection for the Article
    @comment = Comment.new
    # @comment = @article.comments.new
    # Due to the Rails’ mass-assignment protection, the article_id attribute of the new Comment object needs to be manually assigned with the id of the Article
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    # when you call a new article, you can pass it a hash of attributes
    # article.params is like the short-hand for params hash for all attributes the article has
    @article = Article.new(article_params)
    # @article = Article.new(params[:article])
    # params can take a hash inside a hash
    # title: params[:article][:title]
    # body: params[:article][:body]
    @article.save
    # we dont create a new html page here, but we simply direct the create page to the previous show page (since it has article_path(id), which is the "show" action in route)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    # article_params bacuase we need to update every field of the object
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' has been updated!"
    redirect_to article_path(@article)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # comment_params is like a short-hand for the params hash for all attributes the comment has
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save
    # we dont create a new html page here, but we simply direct back to the article where the comment tied to.
    # just like when we call @article.comments - all the comments will show, we can do the same w @comment.article - the article for that comment will show
    redirect_to articles_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # this support  strong params
  def article_params
    # params.require(:article).permit(:title, :body)
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>

  <p class = "comment"><%= comment.body %></p>
    <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<!-- form_for is a Rail helper med which takes 1 parameters and a block of fields. The form is later on refered by name f -->
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
    <li><%= error  %></li>
    <% end %>
  </ul>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <!-- When we added the link_to in the index and pointed it to the article_path for this article, the router created this URL: http://localhost:3000/articles/1 -->
      <!-- article.title is the text you want the link to say -->
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>
 <!-- class is just for CSS -->
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<!-- tagging -->
  <p>
    Tags:
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>

<!-- adding the image -->
<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
</p>

<!--  body -->
<p><%= @article.body %></p>
<!-- articles_path: the route-helper which  -->

<!-- adding comments -->
<h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<!-- Through some JavaScript tricks, Rails can now pretend that clicking this link triggers a DELETE -->
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Are you sure to delete the article?"} %>

<!-- edit article -->
<%= link_to "edit", edit_article_path(@article) %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>